### ISSUE TITLE
UndefRefError in G_.acquisition

### ISSUE THREAD

**Issue by denglerchr** [jwahlstrand/AravisCameras.jl#2]
First of all thanks for the package, its so much easier to work with Aravis than anything else I saw with GeniCAM.
I am currently exploring the library and it seems the "acquire" function is not working propertly. When using it, I get:
```julia
julia> buf = AravisCameras.G_.acquisition(cam, 200)
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] convert_(::Type{ArvBuffer}, ptr::Ptr{ArvBuffer}, owns::Bool)
   @ Gtk4.GLib C:\Users\dengl\.julia\packages\Gtk4\sSQWS\src\GLib\gtype.jl:155
 [2] convert
   @ C:\Users\dengl\.julia\packages\Gtk4\sSQWS\src\GLib\gtype.jl:148 [inlined]
 [3] acquisition(instance::ArvCameraLeaf, _timeout::Int64)
   @ AravisCameras.G_ C:\Users\dengl\.julia\packages\AravisCameras\mW49l\src\gen\aravis_methods:209
 [4] top-level scope
   @ REPL[28]:1
```
Versioninfo:
```julia
Julia Version 1.11.1
Commit 8f5b7ca12a (2024-10-16 10:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, tigerlake)
Threads: 1 default, 0 interactive, 1 GC (on 16 virtual cores)
```

**Comment by jwahlstrand** [comment]
It's good to know someone else is trying to use this package, which is a bit rough around the edges. I do use it myself but have not used this particular method. Clearly the buffer being returned is NULL, which the `convert` method does not handle gracefully. The Aravis documentation suggests NULL is returned when the `error` argument is set. When this happens the Julia method is supposed to throw an exception. It looks like that is not happening and the `convert` method is being called.

Maybe there should be a "nullable" annotation added to the return of this method in Aravis? I'll look into that. For now I will probably override the method in the package so that when NULL is returned, the Julia method will return `nothing`.

**Comment by jwahlstrand** [comment]
There's a new `acquisition` method in the main module that should work. It will return `nothing` when the buffer is NULL. I'll file an issue upstream with Aravis that may eventually fix the auto-generated method.

**Comment by denglerchr** [comment]
Thanks a lot! Looks like I have some issue then with the camera rather than with the library.
